In [66]:
# import module

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression

In [67]:
# read file

file_path = r'C:\Users\황주신\Documents\University\3학년\1학기\01. 인공지능개론\03. 실습, 과제\W9\car+evaluation\car.data'

index = ['Buying', 'Maint', 'Doors', 'Persons', 'Lug_boot', 'Safety', 'Class']

data = pd.read_csv(file_path, header = None)
df = pd.DataFrame(data)

df.columns = index

df

     Buying  Maint  Doors Persons Lug_boot Safety  Class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [68]:
# 결측치 확인
df.isnull().sum()

Buying      0
Maint       0
Doors       0
Persons     0
Lug_boot    0
Safety      0
Class       0
dtype: int64

In [69]:
# module import

from sklearn.preprocessing import LabelEncoder

# 라벨 인코딩 함수
def label_encode(data, column):
    label_encoder = LabelEncoder()
    data[column] = label_encoder.fit_transform(data[column])
    return data

# 데이터(data)와 인코딩할 열(column)을 전달하여 label encoding 수행
data = label_encode(data, 0)
data = label_encode(data, 1)
data = label_encode(data, 4)
data = label_encode(data, 5)
# data = label_encode(data, '')

print(data)

# 인코딩된 열을 DataFrame에 추가
df['Buying_encoded'] = data[0]
df['Maint_encoded'] = data[1]
df['Lug_boot_encoded'] = data[4]
df['Safety_encoded'] = data[5]

# 인코딩 되지 않은 열을 DataFrame에서 삭제
df_encoded = df.drop('Buying', axis = 1)
df_encoded = df_encoded.drop('Maint', axis = 1)
df_encoded = df_encoded.drop('Lug_boot', axis = 1)
df_encoded = df_encoded.drop('Safety', axis = 1)

df_encoded

      0  1      2     3  4  5      6
0     3  3      2     2  2  1  unacc
1     3  3      2     2  2  2  unacc
2     3  3      2     2  2  0  unacc
3     3  3      2     2  1  1  unacc
4     3  3      2     2  1  2  unacc
...  .. ..    ...   ... .. ..    ...
1723  1  1  5more  more  1  2   good
1724  1  1  5more  more  1  0  vgood
1725  1  1  5more  more  0  1  unacc
1726  1  1  5more  more  0  2   good
1727  1  1  5more  more  0  0  vgood

[1728 rows x 7 columns]

,Doors,Persons,Class,Buying_encoded,Maint_encoded,Lug_boot_encoded,Safety_encoded
0,2,2,unacc,3,3,2,1
1,2,2,unacc,3,3,2,2
2,2,2,unacc,3,3,2,0
3,2,2,unacc,3,3,1,1
4,2,2,unacc,3,3,1,2
...,...,...,...,...,...,...,...
1723,5more,more,good,1,1,1,2
1724,5more,more,vgood,1,1,1,0
1725,5more,more,unacc,1,1,0,1
1726,5more,more,good,1,1,0,2
1727,5more,more,vgood,1,1,0,0

In [76]:
# doors에 5more을 5로 변경하기
df_encoded['Doors'] = df_encoded['Doors'].replace('5more', 5)

# persons에 more을 6으로 변경하기
df_encoded['Persons'] = df_encoded['Persons'].replace('more', 6)

In [77]:
X = df_encoded.drop('Class', axis = 1)
Y = df['Class']

print(X.head())
print()
print(Y.value_counts())

  Doors Persons  Buying_encoded  Maint_encoded  Lug_boot_encoded  \
0     2       2               3              3                 2
1     2       2               3              3                 2
2     2       2               3              3                 2
3     2       2               3              3                 1
4     2       2               3              3                 1

   Safety_encoded
0               1
1               2
2               0
3               1
4               2

Class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [78]:
# split X_train, Y_train, X_test, Y_test

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [79]:
from sklearn.linear_model import LogisticRegression
import numpy as np

clf = LogisticRegression()

# 학습
clf.fit(X_train, Y_train)

# 테스트 데이터로 예측
y_pred= clf.predict(X_test)

# 정확도 계산
print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(Y_test, y_pred))
print (confusion_matrix(Y_test, y_pred))

--- Logistic Regression Classifier ---
0.6502890173410405
[[  9   0  67   3]
 [  1   0  16   0]
 [ 22   0 214   4]
 [  2   0   6   2]]

c:\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [80]:
# DecisionTree

from sklearn.tree import DecisionTreeClassifier
import numpy as np

clf = DecisionTreeClassifier(random_state=0)

# 학습
clf.fit(X_train, Y_train)

# 테스트 데이터로 예측
y_pred= clf.predict(X_test)

# 정확도 계산
print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(Y_test, y_pred))
print (confusion_matrix(Y_test, y_pred))

--- Logistic Regression Classifier ---
0.9682080924855492
[[ 71   4   4   0]
 [  0  17   0   0]
 [  2   0 238   0]
 [  1   0   0   9]]

In [81]:
# RandomForest

from sklearn.ensemble import RandomForestClassifier
import numpy as np

clf = DecisionTreeClassifier(random_state=0)

# 학습
clf.fit(X_train, Y_train)

# 테스트 데이터로 예측
y_pred= clf.predict(X_test)

# 정확도 계산
print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(Y_test, y_pred))
print (confusion_matrix(Y_test, y_pred))

--- Logistic Regression Classifier ---
0.9682080924855492
[[ 71   4   4   0]
 [  0  17   0   0]
 [  2   0 238   0]
 [  1   0   0   9]]